include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = subclassing
subclassing_OBJC_FILES = main.m weapon.m gun.m knife.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
