#!/usr/bin/env ruby

require 'gtk2'

window = Gtk::Window.new
window.border_width = 6

window.signal_connect("delete_event") do
  false
end

window.signal_connect("destroy") do
  Gtk.main_quit
end

button = Gtk::Button.new('Button')

button.signal_connect('clicked') do
  puts 'Button was clicked!'
end

window.add(button)
window.show_all

Gtk.main
