include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = threads_condition
threads_condition_OBJC_FILES = main.m producer.m consumer.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
