include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = protocol
protocol_OBJC_FILES = main.m coke-in-can.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
