include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = mutable
mutable_OBJC_FILES = main.m device.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
