include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = multiple
multiple_OBJC_FILES = main.m ball.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
