include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = informal_protocol
informal_protocol_OBJC_FILES = main.m coke-machine.m candy-machine.m candy-machine-dispenser.m coke-machine-dispenser.m exploiter.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
