include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = mixing
mixing_C_FILES = buffer.c
mixing_OBJC_FILES = main.m container.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
