include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = threads_simple
threads_simple_OBJC_FILES = main.m runner.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
