include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = coding_style
coding_style_OBJC_FILES = main.m MYObject.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
