include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = categories
categories_OBJC_FILES = main.m nsstring.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
