include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = logging
logging_OBJC_FILES = main.m sample-object.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
