include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = nserror
nserror_OBJC_FILES = main.m bottle.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
